apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-acoount-token
data:
#you can include additional key value pairs as you do with opaque secrets
  extra: YmFyCg==