---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: yum update
    yum:
      name: '*'
      state: latest
  - name: Install java
    yum:
      name: java-11-amazon-corretto-11.0.5+10-1.amzn2.x86_64
      state: present
  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes
  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  - name: Install git
    yum:
      name: git
      state: present
  - name: Install maven
    yum:
      name: maven
      state: present
  - name: Install docker
    yum:
      name: docker
      state: present
  - name: start docker
    service:
      name: docker
      state: started
  - name: Install wget
    yum:
      name: wget
      state: present
  - name: Install vim
    yum:
      name: vim
      state: present
